### ISSUE TITLE
Failing runs report as green in the Overview and unchanged on Nodes page.

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/puppetboard#360]
I had a catalog that failed to compile and run and Puppetboard did not flag the issue.

```
$ sudo puppet agent -t
[sudo] password for rnelson0:
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for jenkins.nelson.va
Info: Applying configuration version '1486954936'
Error: Failed to apply catalog: undefined method `split' for ["ruby-2.3.1"]:Array
```

```
0 nodes
with status failed 
```

**Comment by rnelson0** [comment]
Dashboard (note the bad change was introduced between 2-3 days ago and the run counts are the same per day):

http://imgur.com/a/NTTsy

Node view:

http://imgur.com/a/Li8hV

This is with puppetboard 0.2.0 installed through [puppet-puppetboard](https://forge.puppet.com/puppet/puppetboard).

**Comment by mterzo** [comment]
@rnelson0 because you have daily graphs you aren't running 0.2.0, you are running either 0.2.1 or off of git master.

PR went into today that is going to stop that confusion. When we release a point release we will up the version in master so that it's clear what version folks are running.

There was some issues what was recently fixed with a bump in pypupetdb 0.3.2.  So I looked at puppet-puppetboard, I'm not 100% sure if the requirements.txt file gets updated that it will run pip
and install the new dependencies, thats part of the python module.  I'm not crazy that it's just pulling down git and running latest off of master, would rather it use the pypi repo, that's a discussion to have in another forum.

If you are still running the old version of pypupetdb, please update to 0.3.2 in that virtualenv that puppet-puppetboard is using, we need fix that module if that's the case.

If that's not the problem:

I've tested with both master, 0.2.0 and 0.2.1 docker container.  I added a simple error in my site.pp

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::broken for 34d348bd9984.internal.terzo.org at /etc/puppetlabs/code/environments/production/manifests/site.pp:3:3 on node 34d348bd9984.internal.terzo.org
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

This error is reporting correctly in puppetboard.

I find that it's being reported in PuppetDB:

```
# Run this on your puppetdb server.
curl -X GET http://localhost:8080/pdb/query/v4/reports \
    -d 'query=["and", ["=", "status", "failed"], ["=", "certname", "34d348bd9984.internal.terzo.org"]]'

[
  {
    "cached_catalog_status": "not_used",
    "catalog_uuid": null,
    "certname": "34d348bd9984.internal.terzo.org",
    "code_id": null,
    "configuration_version": "",
....
    "logs": {
      "data": [
...
        {
          "file": null,
          "level": "err",
          "line": null,
          "message": "Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::broken for 34d348bd9984.internal.terzo.org at /etc/puppetlabs/code/environments/production/manifests/site.pp:3:3 on node 34d348bd9984.internal.terzo.org",
          "source": "Puppet",
          "tags": [
            "err"
          ],
          "time": "2017-02-13T06:01:26.449590846+00:00"
        },
...
    "start_time": "2017-02-13T06:01:19.574Z",
    "status": "failed",
    "transaction_uuid": "10ea154c-379d-420d-aff0-b11154701aa4"
  }
```

If the above query with your certname does not show any results then puppet is not reporting back to puppetdb.  If it does, I would love to have the data, so I can add it to a test case.

**Comment by rnelson0** [comment]
It doesn't look like it's reporting back, or at least isn't reporting to where you'd think:

```
[rnelson0@puppet ~]$ curl -X GET http://localhost:8080/pdb/query/v4/reports \
>     -d 'query=["and", ["=", "status", "failed"], ["=", "certname", "jenkins.nelson.va"]]'
[][rnelson0@puppet ~]$
 curl -X GET http://localhost:8080/pdb/query/v4/reports     -d 'query=["and", ["=", "status", "failed"], ["=", "certname", "build02.nelson.va"]]'
[][rnelson0@puppet ~]$ rpm -qa | grep puppet
puppetlabs-release-pc1-1.1.0-2.el7.noarch
puppetserver-2.3.0-1.el7.noarch
puppetdb-4.3.0-1.el7.noarch
puppet-agent-1.9.1-1.el7.x86_64
puppetdb-termini-4.3.0-1.el7.noarch
```

**Comment by mterzo** [comment]
If the agent has checked in once it should be going to unreported.

**Comment by rnelson0** [comment]
It definitely has been checked in for weeks at this point. Very odd.

If you think this is fixed in a newer version, and I can deploy it with
puppet-puppetboard, let me know and I'll try that before going any further.

**Comment by mterzo** [comment]
I'm not sure there's a fix here, If the agent/server doesn't generate a report then it won't show up.

Let's see what the last report was:
```
curl -X GET http://localhost:8080/pdb/query/v4 \
    --data-urlencode 'query=["from", "reports", 
    ["=", "certname", "jenkins.nelson.va"], 
    ["order_by", [["end_time", "desc"]]], ["limit", 1]]'
```

**Comment by rnelson0** [comment]
```
$ sudo puppet agent -t --environment=test
Info: Using configured environment 'test'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for build03.nelson.va
Info: Applying configuration version '1487014893'
Error: Failed to apply catalog: undefined method `split' for ["ruby-2.3.1"]:Array


$ curl -X GET http://localhost:8080/pdb/query/v4     --data-urlencode 'query=["from", "reports",
    ["=", "certname", "build03.nelson.va"],
    ["order_by", [["end_time", "desc"]]], ["limit", 1]]'
[{"catalog_uuid":"0406f6e3-b0a9-41aa-9a1a-1b39c259b3cb","receive_time":"2017-02-13T19:41:39.991Z","producer":null,"hash":"d788afcea7ef430ef1a179d0684854a7d8ffffb2","transaction_uuid":"0406f6e3-b0a9-41aa-9a1a-1b39c259b3cb","puppet_version":"4.9.2","noop":false,"corrective_change":null,"logs":{"data":[{"file": null, "line": null, "tags": ["info"], "time": "2017-02-13T19:41:28.559986432+00:00", "level": "info", "source": "Puppet", "message": "Using configured environment 'test'"}, {"file": null, "line": null, "tags": ["info"], "time": "2017-02-13T19:41:28.560247770+00:00", "level": "info", "source": "Puppet", "message": "Retrieving pluginfacts"}, {"file": null, "line": null, "tags": ["info"], "time": "2017-02-13T19:41:28.667902281+00:00", "level": "info", "source": "Puppet", "message": "Retrieving plugin"}, {"file": null, "line": null, "tags": ["info"], "time": "2017-02-13T19:41:31.288523746+00:00", "level": "info", "source": "Puppet", "message": "Loading facts"}, {"file": null, "line": null, "tags": ["info"], "time": "2017-02-13T19:41:38.939484864+00:00", "level": "info", "source": "Puppet", "message": "Caching catalog for build03.nelson.va"}, {"file": null, "line": null, "tags": ["info"], "time": "2017-02-13T19:41:39.515474910+00:00", "level": "info", "source": "Puppet", "message": "Applying configuration version '1487014893'"}, {"file": null, "line": null, "tags": ["err"], "time": "2017-02-13T19:41:39.682966648+00:00", "level": "err", "source": "Puppet", "message": "Failed to apply catalog: undefined method `split' for [\"ruby-2.3.1\"]:Array"}],"href":"/pdb/query/v4/reports/d788afcea7ef430ef1a179d0684854a7d8ffffb2/logs"},"report_format":6,"start_time":"2017-02-13T19:41:28.115Z","producer_timestamp":"2017-02-13T19:41:39.716Z","cached_catalog_status":null,"end_time":"2017-02-13T19:41:34.200Z","resource_events":{"data":null,"href":"/pdb/query/v4/reports/d788afcea7ef430ef1a179d0684854a7d8ffffb2/events"},"status":"unchanged","configuration_version":"1487014893","environment":"test","code_id":null,"noop_pending":null,"certname":"build03.nelson.va","metrics":{"data":[{"name": "changed", "value": 0, "category": "resources"}, {"name": "corrective_change", "value": 0, "category": "resources"}, {"name": "failed", "value": 0, "category": "resources"}, {"name": "failed_to_restart", "value": 0, "category": "resources"}, {"name": "out_of_sync", "value": 0, "category": "resources"}, {"name": "restarted", "value": 0, "category": "resources"}, {"name": "scheduled", "value": 0, "category": "resources"}, {"name": "skipped", "value": 0, "category": "resources"}, {"name": "total", "value": 0, "category": "resources"}, {"name": "config_retrieval", "value": 6.084486018, "category": "time"}, {"name": "total", "value": 6.084486018, "category": "time"}, {"name": "total", "value": 0, "category": "changes"}, {"name": "failure", "value": 0, "category": "events"}, {"name": "success", "value": 0, "category": "events"}, {"name": "total", "value": 0, "category": "events"}],"href":"/pdb/query/v4/reports/d788afcea7ef430ef1a179d0684854a7d8ffffb2/metrics"}}]
```

```
# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
backports.ssl-match-hostname (3.4.0.2)
configobj (4.7.2)
decorator (3.4.0)
Flask (0.10.1)
Flask-WTF (0.12)
iniparse (0.4)
itsdangerous (0.23)
Jinja2 (2.7.2)
MarkupSafe (0.19)
perf (0.1)
pip (9.0.1)
pycurl (7.19.0)
pygobject (3.14.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pypuppetdb (0.3.2)
pyudev (0.15)
pyxattr (0.5.1)
requests (2.6.0)
setuptools (32.3.1)
slip (0.4.0)
slip.dbus (0.4.0)
urlgrabber (3.10)
virtualenv (1.10.1)
Werkzeug (0.11.10)
WTForms (2.1)
yum-metadata-parser (1.1.4)
```

Verified the puppetboard revision is set to v0.2.1 and that the upgrade completed. I restarted httpd manually and verified the status remains green and the node shows Unchanged.

**Comment by mterzo** [comment]
Ok, this is awkward.  All our queries rely on that fact that the status of the node failed in this case.  In what we are getting from puppetdb it's just unreported.  All our generic queries that ask for failed, changed, etc will be wrong.  Need to submit a bug to puppet on this.

I'm looking at what's the best way to deal with that now.

**Comment by redref** [comment]
Just noticed puppetserver is older than agent and db. I'm not that up to date but already had problems with non coherent versions.

Worth a try.

**Comment by mterzo** [comment]
We had the conversation on IRC.  You are running a very old version of the server.

**Comment by emlun007** [comment]
#449

**Comment by gdubicki** [comment]
Closing as outdated. Please reopen if you still experience such problem with the current version of the Puppetboard.
